backend:
  name: git-gateway
  branch: main

media_folder: "images/blog"
public_folder: "/images/blog"

locale: "tr"

collections:
  - name: "blog"
    label: "Blog Yazıları"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Başlık", name: "title", widget: "string" }
      - { label: "Yayın Tarihi", name: "date", widget: "datetime" }
      - { label: "Kategori", name: "category", widget: "string" }
      - { label: "Özet", name: "excerpt", widget: "text" }
      - { label: "Kapak Görseli", name: "thumbnail", widget: "image", required: false }
      - { label: "İçerik", name: "body", widget: "markdown" }
